apiVersion: v1
data:
  index.html: |-
    <!DOCTYPE html>
    <html>
    <head>
    <title>staging</title>
    </head>
    <body>

    <h1>staging</h1>

    </body>
    </html>
kind: ConfigMap
metadata:
  name: kargo-demo-content
